version: '3'

services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9191:9191"
    depends_on:
      - mysql-db

  mysql-db:
    build:
      context: .
      dockerfile: Dockerfile-mysql
